name: bling_api
description: Bling API client library
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  test: ^1.24.0
  openapi_generator_annotations: any

dev_dependencies:
  lints: ^2.1.0
  openapi_generator: ^6.1.0
  build_runner: ^2.4.11